### ISSUE TITLE
Filter not working in Hierarchy

### ISSUE THREAD

**Issue by agarg94** [w11k/w11k-select#44] opened 2017-11-04 19:40 UTC
* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
The filter does not seem to work for demo hierarchy. Basically you can search/filter for the top level but not any sub-level like "GrandChild1a". Could you please take a look?

Thanks.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by pburgmer** [comment] 2017-11-14 12:33
Hi,

Thanks for your bug report. We have a lot of work to do right now so it will may take some time to fix it.
@CanKattwinkel could you take a look at this please.

**Comment by CanKattwinkel** [comment] 2018-01-03 13:07
The issue is fixed with version 0.11.2 that I just published to npm and bower.

![image](https://user-images.githubusercontent.com/11500619/34521676-4a931422-f08f-11e7-98bd-66919657e148.png)

**Closed by CanKattwinkel** 2018-01-03 13:07 UTC
