### ISSUE TITLE
Default value for multiselect mode

### ISSUE THREAD

**Issue by gabooo** [w11k/w11k-select#18] opened 2015-04-03 13:28 UTC
Hi,

I've encountered a problem when I try to load a saved state to the selector. I use: 

<div id="multiSelectBooks"
                ng-show="IsScenariosVisible"
                class="horizontalLayout"
                w11k-select
                w11k-select-config="multiSelectScenarioConfig"
                w11k-select-options="o as o.description for o in scenarios"
                ng-model="SelectedScenarios" />

When scenarios are loaded and the selector is populated, I would like to select all the item by default (or load a persisted state back to the selector). 

I try to use this code:

$scope.SelectedScenarios = $scope.scenarios

But when I set the selected scenarios this way, it gets cleared and nothing will be selected. I debugged the code and found out that the selected scenarios is set well and after that something clears out (watch gets called two time).

Do you have any idea what can cause this behavior?

Thanks,

Gabor

**Comment by pburgmer** [comment] 2015-04-07 07:14
Hi,

Which version are you using? Perhaps this is a duplicate of #9. The problem was setting options and selection in the same time (same digest lifecycle). The new options will override the selection. But it should be fixed.

Can you reproduce this behaviour and share a plunker? Thanks.

**Comment by pburgmer** [comment] 2015-04-07 10:49
Can you try out this workaround:
Wrap the assignment of the selected values (ng-model) in a function and use $timeout to call this function.

Something like this:
```
$timeout(function() {
  $scope. SelectedScenarios = $scope.scenarios;
});
```

**Comment by gabooo** [comment] 2015-04-07 11:08
Hi, 

Thanks for your quick answer. I'm using v0.6.0. I will try to do a plunker, but workaround with timer is working correctly.

Thanks.

**Comment by pburgmer** [comment] 2016-02-02 22:25
Works with 0.6.2.

**Closed by pburgmer** 2016-02-02 22:25 UTC

**Comment by pburgmer** [comment] 2016-03-15 11:08
Hi @gabooo,

If you're using w11k-select and like it, please think about giving an 'I use it' at ngmodules.org
http://ngmodules.org/modules/w11k-select

Thanks & regards,
Philipp
